# Generated by Django 3.1.2 on 2021-12-27 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='members',
            field=models.ManyToManyField(related_name='tags', to='articles.Article', verbose_name='Раздел'),
        ),
    ]
